# Generated by Django 5.0.4 on 2024-05-03 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='destinations/')),
            ],
        ),
        migrations.CreateModel(
            name='OffreSpeciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offre_speciale', models.BooleanField(default=False)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.destination')),
            ],
        ),
        migrations.CreateModel(
            name='EvenementTouristique',
            fields=[
                ('destination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.destination')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('offre_speciale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.offrespeciale')),
            ],
            bases=('core.destination',),
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('destination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.destination')),
                ('capacite', models.IntegerField()),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offre_speciale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.offrespeciale')),
            ],
            bases=('core.destination',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('destination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.destination')),
                ('type_cuisine', models.CharField(max_length=100)),
                ('tarif_moyen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offre_speciale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.offrespeciale')),
            ],
            bases=('core.destination',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('destination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.destination')),
                ('type_transport', models.CharField(choices=[('Bus', 'Bus'), ('Train', 'Train'), ('Avion', 'Avion'), ('Bateau', 'Bateau')], max_length=10)),
                ('disponibilite', models.BooleanField(default=True)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offre_speciale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.offrespeciale')),
            ],
            bases=('core.destination',),
        ),
    ]
