# Generated by Django 5.0.4 on 2024-05-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='type_transport',
            field=models.CharField(choices=[('Car', 'Car'), ('Train', 'Train'), ('Avion', 'Avion'), ('Bateau', 'Bateau')], max_length=10),
        ),
    ]
